### ISSUE TITLE
2021-12-07 08:50:03.862 [CRT] PROT: Stack trace: goroutine 140 [running]: runtime/debug.Stack(0x43b5e3d, 0x22, 0xc020269b38)

### ISSUE THREAD

**Issue by mtmtmt123** [kaspanet/docs#34]
Hello, i have the error if i write utxoindex after all synched and mined.
if i delete datadir2 it works
but no balance
how can i login to my wallet again?

**Comment by someone235** [comment]
Can you paste the full error?

**Comment by someone235** [comment]
And please move this issue to https://github.com/kaspanet/kaspad
