### ISSUE TITLE
Document on the main website when mainnet is estimated to launch

### ISSUE THREAD

**Issue by ripper234** [kaspanet/docs#9]
I believe mainnet hasn't launched yet, only testnet, right?

[The homepage](https://www.daglabs.com/) describes Kaspa as a **fair launch** instant confirmation transaction sequencing layer. To me, fair launch includes publishing way way in advance, in a public way (e.g. on the homepage) when the mainnet launch will be.

Has the date been decided/estimated already?

**Comment by hashdag** [comment]
Right, we are just testnet now. Mainnet will launch when a testenet version will be bug free and stable for a meaningful period of time; I guesstimate 3-5 months from today. Do you recommend a different process?

BTW AFAIK there is no homepage for Kaspa

**Comment by ripper234** [comment]
@hashdag I see, this seems great & fair indeed. Closing.
